remote_theme: vaibhavvikas/jekyll-theme-minimalistic
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

# describe
title: 数理研究同好会
description: ホームページへようこそ！
logo: /img/tylogo.jpg
color-scheme: auto
favicon: true
# sidebar
platforms:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/Yanagi3456
  - name: LinkedIn
    icon: <i class="fa-brands fa-linkedin"></i>
    link: 
  - ...
